### ISSUE TITLE
Improve for add token screens

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#104]
- [x] Improve UI for (+) button.
- [x] Change cancel token to the X button in top bar. 
- [x] Follow/unfollow icon are shown in list token. ( Show to user knows which is followed or not).
- [x] Add custom token: networks should be shown clearly in UI network chain. 
- [x] Improve UI when selecting a network in "Add manually " screen.

**Comment by 0xmoehau** [comment]
@keresh93v  will be done in 11/22/2019
