### ISSUE TITLE
My nodes screen still show Tab here to stake after staking success

### ISSUE THREAD

**Issue by thaibao-incognito** [incognitochain/incognito-wallet#106]
**_From: thaibao-incognito_**
**_Bug:_**
My nodes screen still show 'Tab here to stake' after staking success

**_Expected Behavior:_**
Not show

**_Steps to replicate:_**
1/ Add virtual node
2/ Click "Tab here to stake"
3/ Stake with Account 0 by click "Run"
4/ Back screen
5/ Still show 'Tab here to stake'
6/ But "Run" is invisible

**Comment by 0xmoehau** [comment]
fixed. 
and we will change ui mynode at #264  #275
