### ISSUE TITLE
Show Offline after coming into waiting list when swapped

### ISSUE THREAD

**Issue by thaibao-incognito** [incognitochain/incognito-wallet#112]
From: thaibao-incognito
Bug:
My nodes screen still show 'Offline' after coming into waiting list when swapped

Expected Behavior:
Show other things 
as Offline if can not connect node
as Syncing if syncing data
as Waiting if the pending validator

Steps to replicate:
1/ Being committee of shard 7
2/ After swapping out of committee -> come in waiting list again

**Comment by 0xmoehau** [comment]
closed, duplicate to #264
