### ISSUE TITLE
sometimes, when using the wallet app which is backed to the instruction screen

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#120]
Second, when closing the app and opening again. This case can happen.

**Comment by Dream0895** [comment]
<img width="310" alt="Screen Shot 2019-11-20 at 7 49 01 PM" src="https://user-images.githubusercontent.com/57382380/69240348-d7358980-0bce-11ea-9ccc-7b2b7f35e6d2.png">

**Comment by 0xwendigo** [comment]
it fixed in build 3.2.7. please it.
