### ISSUE TITLE
"connectDevice fail" when installing Physical Node

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#127]
User: 7plus11is711@gmail.com
Iphone 10
iOS: 13.1.2
He is using Wallet app version 3.2.6 to set up the Physical Node. After scanning the Node's QR code, a message "connectDevice fail" appears and the app keeps loading. Please see the attachment.
[Clip.zip](https://github.com/incognitochain/incognito-wallet/files/3874144/Clip.zip)

**Comment by Just-m** [comment]
It seems people are not fully aware how the flow should be.
What I got from another user is, you need to connect your device (phone) to the network the node belongs to after starting it up. Away from your own wifi. Once you do that you can connect to the node and update the node settings to match with your own wifi settings.

**Comment by peterincognito** [comment]
user +84 966112385 had "connectDevice fail"
LG G6
Android 7
![photo_2019-11-28_15-14-59](https://user-images.githubusercontent.com/57339122/69788921-090fa700-11f2-11ea-9fea-85bf53ee8c44.jpg)
![photo_2019-11-28_15-14-53](https://user-images.githubusercontent.com/57339122/69788959-1fb5fe00-11f2-11ea-81ef-73a929378c33.jpg)

**Comment by peterincognito** [comment]
User @bangyu
Iphone 10R
OS: 12.3.1
It keeps loading and can not connect to the wifi network. Attachment is the screen record.
[IMG_3830.zip](https://github.com/incognitochain/incognito-wallet/files/3903816/IMG_3830.zip)

**Comment by 0xwendigo** [comment]
fixed for ios 13
