### ISSUE TITLE
App is crashed when going to previous state

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#128]
With an iPhone, you can go back to a previous window by swiping your finger from left to right, it forces the app to be crashed.

Device: iPhone 8 iOS 13.2.2
Device: iPhone 8 iOS 12.1.4
App version: 12.1.4

Please help to investigate.

**Comment by 0xwendigo** [comment]
I have known this, it has happened with iphone. I will fix later.
