### ISSUE TITLE
It keeps loading when sending PRV transaction

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#130]
User: @zes333
Device: Samsung s8
OS: Android 9
The screen keeps loading so he can not send 1000 PRV to another account. Please see the attachment: https://drive.google.com/open?id=1Pg_8lmpov2nEdrIQH8do1biCiAbX9VRr

**Comment by peterincognito** [comment]
User: @bluemoose_ben
Device: iPhone XS Max
OS: 13.2.3
App 3.2.7 & 3.2.8
He sent 1750 PRV from 12RvouDMwBPV7xPuPEzRbu6vtwku5U1Fhg3LhT6M1AxXgGiH2fmVKsUPAGRPrRnRVmadADqWh5sNdYZd4uXed9Z4fLE4yD4RkrB5Y9u to 12S4qdE9KFv7rXr62aHs2qnU3zh9pyFTqgBKEL8vAuAxs1t9x5cso68wPh5ELy71WW8Qqjm4CyACHdWGJGBoc7jSR18zv5fWDEtGAyj
His transaction is loading for hours
![photo_2019-11-25_10-24-45](https://user-images.githubusercontent.com/57339122/69519113-c351a500-0f8b-11ea-9606-e8ca0a8c39cb.jpg)

**Comment by annie-incognito** [comment]
send from:

12S1E5CFBT6V6WU977JYZN67JWQuMvXaA5mRTNWvzmUcpRLoz1PDWnnGvHDaPizo194Y6ferWb8ZMEqzdZYTjizbsZPCNL4s3MjpMJi

to this: 

12S1bWFHAU3d11zSTpMMD1PdF6TtSPXpxDsDaP6kmccEADqxhPZYv4yAqhLC6jdc6Rd7TMEznQLuHhT7PZykUWbLhJmoqScoLWTanxJ

stuck at loading screen 30%
