### ISSUE TITLE
Sha256 checksum missing

### ISSUE THREAD

**Issue by matt6412** [incognitochain/incognito-wallet#1320]
Need sha256 checksum for latest version of Android binary

**Comment by matt6412** [comment]
this is the sha256 checksum I get

246ba864a2b1b990846e65ceea802e56f6951ad8b0cbeb82e6c20bdffbe6d89b

please verify and add to binary read me and preferably GPG sign the hash

**Comment by 0xSiris** [comment]
I have added the sha256 for the newest release
