### ISSUE TITLE
Estimate fee sometimes works incorrectly

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#134]
When just open app, this bug happens when sending/withdrawing/trading/removing money and network is slow

**Comment by Dream0895** [comment]
<img width="308" alt="Screen Shot 2019-11-22 at 5 30 29 PM" src="https://user-images.githubusercontent.com/57382380/69418729-d840f500-0d4d-11ea-849e-c59c52c00424.png">

**Comment by annie-incognito** [comment]
can't send:

video_2019-12-16_12-09-28.mp4

**Comment by annie-incognito** [comment]
@pzs15

![image](https://user-images.githubusercontent.com/56621844/70880826-ffad7980-1ffc-11ea-8391-f0aea15cac7b.png)

**Comment by annie-incognito** [comment]
from: @Rezwan555

![image](https://user-images.githubusercontent.com/56621844/70880871-34b9cc00-1ffd-11ea-829e-4c7c03204132.png)

**Comment by annie-incognito** [comment]
From: @jobair4
![image](https://user-images.githubusercontent.com/56621844/70965600-c9d2c880-20c2-11ea-8ba3-bde6e2b7b685.png)
