### ISSUE TITLE
Withdraw processing  - lack of info 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#139]
From Jamie:
Description:
Doesn’t seem to know the account the funds are going to

Log: 
![image](https://user-images.githubusercontent.com/56621844/69508570-d1da9500-0f68-11ea-8d69-bdcdc35ad2a9.png)

**Comment by 0xSiris** [comment]
This issue happened due to https://github.com/incognitochain/incognito-wallet/issues/141
