### ISSUE TITLE
App crashed 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#140]
From Jamie
Description: 
There is someone with an iPhone 7, using the 3.2.7 version of the wallet app, but the app closes as soon as he presses Send.
It happens when he tries to send PRV to another account, but also when he wants to deposit PRV to pDEX

tried everything, delete app, turn phone off, turn on, reinstall
nothing seems to work
I wondered if it was related to memory or storage but he says that is all fine.

**Comment by 0xSiris** [comment]
It tested on Iphone 7 iOS 13.2 and it worked correctly on 3.2.9
