### ISSUE TITLE
Withdraw screen - not show up still processing

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#141]
From: Ross Taylor
Description:

Update: so I used the new updated iOS app to deposit BTC and the deposit into trading and then buy PRV. When I went to withdraw the PRV to my wallet this screen hung and I had to exit out.
I then checked the history and it showed that it the withdrawal was being processed

Log:

![image](https://user-images.githubusercontent.com/56621844/69509015-0ac73980-0f6a-11ea-9fc6-e5a70d73c7fb.png)

**Comment by annie-incognito** [comment]
![image](https://user-images.githubusercontent.com/56621844/69509060-2c282580-0f6a-11ea-96c4-c5b2df0f3771.png)
undefined account

**Comment by 0xSiris** [comment]
This issue happened on all iOS devices. I'm fixing it. It will be done on November, 27
