### ISSUE TITLE
Can not use this token for fee, please try another

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#145]
User @Makemoney2014
After entering the withdrawal amount, there is a message "Can not use this token for fee, please try another". Please help to explain.
![photo_2019-11-23_10-07-17](https://user-images.githubusercontent.com/57339122/69510172-5380f180-0f6e-11ea-81a4-593413344204.jpg)

**Comment by 0xmoehau** [comment]
duplicate with #134
