### ISSUE TITLE
number of decimals btc 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#146]
![image](https://user-images.githubusercontent.com/56621844/69510656-61d00d00-0f70-11ea-84b3-459af10c0724.png)

**Comment by keresh93v** [comment]
- All amount in the app will follow this rule:
  - Amount < 1 => show full (Ex: 0.00000001)
  - Amount > 1 => round down 4 digits (Ex: 123.345678 => 123.3456)
- Allow send/withdraw small amount, min is 1 nano of the token (currently must be larger than 0.0001)
