### ISSUE TITLE
Link Node to the wallet (when the node removed)

### ISSUE THREAD

**Issue by hoangphuongcs** [incognitochain/incognito-wallet#148]

**Comment by hoangphuongcs** [comment]
- [ ] API get device info: @hoangphuongcs 
- [ ] App: @0xwendigo

**Comment by 0xwendigo** [comment]
App: 
(1)Disable remove NODE in Home screen.
(2)Disable factory reset 
(3)Change lable: node's name -> qrcode
(4)Call api to create model NODE to link node which was earning.

**Comment by 0xwendigo** [comment]
(1) (2) (3) will release in build 3.2.9.
