### ISSUE TITLE
pBTC is not shown up in wallet

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#149]
User: @tylerking
In Node detail screen, he withdrew his earning from staking (PRV and pBTC) to his wallet:
12RrzXspWzBJKfWvfeUXaSz9xHPt19mJsk7TECGqMvefL6YQHZ8iKRsy5sRxytVNk4yT4Ee17Jf9uVTxZgpZ8V3rerqgBVQhC6WFkPR
The earned PRV is credited to his wallet, but he hasn't received pBTC for 10 hours already.

**Comment by 0xmoehau** [comment]
closed, move to incognito-chain issue.

**Comment by 0xmoehau** [comment]
vhttps://github.com/incognitochain/incognito-chain/issues/600
