### ISSUE TITLE
Upload Icon for Lunch Money token

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-wallet#15]
### FROM
https://t.me/Jeff3000

### ISSUE
Jeff Varnado, [Nov 2, 2019 at 1:08:11 PM]:
Hello @duy_incognito

@Jamie_Incognito sent me

I'm the founder lunchmoney.io

Can you add the Lunch Money icon?

duy ~ incognito.org, [Nov 2, 2019 at 8:20:47 PM]:
hey.  can you send me your icon?  we'll have to upload manually for now.

Jeff Varnado, [Nov 2, 2019 at 8:22:22 PM]:
Yes coming right up.

![image](https://user-images.githubusercontent.com/4691695/68083069-764a3b00-fdf2-11e9-8400-10105452e252.png)

![image](https://user-images.githubusercontent.com/4691695/68083072-79452b80-fdf2-11e9-8e51-dca863dac757.png)

**Comment by hoangphuongcs** [comment]
done!
