### ISSUE TITLE
Upload icon for incognito token + save token info

### ISSUE THREAD

**Issue by keresh93v** [incognitochain/incognito-wallet#158]

**Comment by hoangphuongcs** [comment]
backend finish: Dec 11

**Comment by hoangphuongcs** [comment]
type: png
size < 50 kb
(circle photo)

**Comment by hoangphuongcs** [comment]
some response from api:
![image](https://user-images.githubusercontent.com/4811620/70515263-a3afa480-1b67-11ea-9bc2-d2fd45b05721.png)
