### ISSUE TITLE
Sometimes, app is crashed when using

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#175]
For now, we don't have steps. we are investigating the root cause.
We have some steps when crashing the app below:
- After sending money, back to wallet screen=> selecting Pdex=> crash app.
- After switching between account => crash app
- After withdrawing, selecting Pdex => crash app
- After trading, selecting Wallet => crash app
- After import account, selecting Wallet => crash app

----
will improve performance app.

**Comment by annie-incognito** [comment]
app stopped when deposit into pDEX 

![image](https://user-images.githubusercontent.com/56621844/70972580-49b65e00-20d6-11ea-8fda-f36b8f7e260e.png)

**Comment by annie-incognito** [comment]
same: app stopped when depositing into pDEX

![image](https://user-images.githubusercontent.com/56621844/70972664-766a7580-20d6-11ea-86ac-cc07c2790af3.png)

**Comment by Just-m** [comment]
![image](https://user-images.githubusercontent.com/5701553/70980124-0d253b00-20b3-11ea-9e01-2646d57198c7.png)
The app shuts down when trying to deposit to pDEX
 J7Max, SM-G615F, Android 8.1.0, Incognito app 3.4.1
(If needed, account address on Slack)
