### ISSUE TITLE
Update to 4.4.2 not in github?

### ISSUE THREAD

**Issue by jbrepogmailcom** [incognitochain/incognito-wallet#1798]
**Describe the bug**

I downloaded ver. 4.4.1 from github. After launch, it forced update to 4.4.2, but that version is not on github. Does it mean it is not opensource and the source code cannot be checked?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by emanuelb** [comment]
The version on google-play is 4.4.0: https://play.google.com/store/apps/details?id=com.incognito.wallet
Latest tag & github release is 4.4.1: https://github.com/incognitochain/incognito-wallet/tags

There is branch for 4.4.2 release at:
https://github.com/incognitochain/incognito-wallet/blob/release/4.4.2/android/app/build.gradle

But the VersionName is 4.4.0 and not 4.4.2:
https://github.com/incognitochain/incognito-wallet/blob/release/4.4.2/android/app/build.gradle#L142

don't know about the in-app update mechanism, will need to wait for someone from incognito to answer this question.

**Comment by jbrepogmailcom** [comment]
Thanks it was a bit hard to find 4.4.2
