### ISSUE TITLE
add min amount with 1 nano money for Ptoken

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#195]
Current: Cannot withdraw/ deposit with 1 nano( 0.000000001) for BTC, BNB, ETH, Tomo. 
Expected result: Every coin should limit min money which can withdraw/deposit. 
ETH: 0.009
pBTC: 0.0002
pBNB: 0.07
pTomo: 1

**Comment by hoangphuongcs** [comment]
Need add min amount for withdraw
