### ISSUE TITLE
send feature not working (send to constant + send to pdex)

### ISSUE THREAD

**Issue by screensav3r** [incognitochain/incognito-wallet#207]
USER:
@anhwait1

DESCRIPTION:

send transactions are not processing. user tried to send to constant and send to pdex. fee seems high enough, user tried to restart app to no avail. both transactions have been stuck for about an hour. does not show up in transaction history.

![image](https://user-images.githubusercontent.com/57341808/69895149-9cb5b480-1365-11ea-8f32-e70990837fac.png)

**Comment by 0xSiris** [comment]
This issue is duplicated with #232
