### ISSUE TITLE
Delay pUSDT withdrawal 

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#212]
User @Vin2312 withdraws 0.7 and 1.15 pUSDT to his address: 0xf4e5b2e84f52acb06c76b365e69a194c49b6db52
https://mainnet.incognito.org/tx/28cf32443646802edff4ad005f27577456a43cb68f7726dd2804b3e0141c95aa
https://mainnet.incognito.org/tx/61ad39d55407a00207a64e8bfe74e3ef768545fc7f5ba12d1afa3acca1989f93
He said he didn't receive. 

![photo_2019-12-02_14-38-20](https://user-images.githubusercontent.com/57339122/69939149-b72c9100-1511-11ea-82d7-dd07993aa63d.jpg)

**Comment by hoangphuongcs** [comment]
need the user incognito wallet address

**Comment by hoangphuongcs** [comment]
it's success, pls see erc20 tab
![image](https://user-images.githubusercontent.com/4811620/69943293-d4645e00-1517-11ea-999b-e2a86cb00d8d.png)

**Comment by peterincognito** [comment]
messaged user again
