### ISSUE TITLE
Delay pETH & pBTC withdrawal

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#213]
User @fitz_fiat claims that he doesn't receive these tokens in his wallet
1/ https://mainnet.incognito.org/tx/0478f595004b5483b25a9cc1d14451c7c59045ba5b0db79c077b778855a29f3f
0.373 ETH
Address: 0x754e58E7...
![photo_2019-12-02_14-46-35](https://user-images.githubusercontent.com/57339122/69939603-db3ca200-1512-11ea-9579-a5005a5376f3.jpg)

2/ "When I setup the withdrawal it went to 10% the reported an issue and to try again.  I did this two more times.
Went back to my pDex wallet and into btc and saw the transaction penfing[0].
However it is still in that same status and after canceling the transaction I am not able to transfer to another incognito wallet to try to withdraw from there. 
I am using iOS 3.3.1 version of the app."
![photo_2019-12-02_14-49-29](https://user-images.githubusercontent.com/57339122/69939660-0626f600-1513-11ea-9629-9100c285c0a8.jpg)
![photo_2019-12-02_14-49-33](https://user-images.githubusercontent.com/57339122/69939667-0b844080-1513-11ea-8f65-365ea5f4dc1d.jpg)
![photo_2019-12-02_14-49-38](https://user-images.githubusercontent.com/57339122/69939668-0c1cd700-1513-11ea-8e74-b0d1c4b0429e.jpg)

**Comment by hoangphuongcs** [comment]
can you give me the user incognito wallet address?

**Comment by peterincognito** [comment]
ETH address: 12RvsGSgkT5trVMzXRfru8NTxDMQtzhND8K8adt88aRLco731sWDdn58NdiNbJpTs1g8YgVDu9KpZ2WFBd7zy5zVSAW1cHxUTyBFoLg
BTC address:
12Rr9WKuhve3PguZZpdwgq16DgDwY15Aq3r6hbuw74L8bTxHKxCwxG9HyKBBC9PuJzhvcv99Q3HUbKDVyaSnoQNYEYNcqr4ewhfacPH

**Comment by peterincognito** [comment]
"Ok ETH withdrawal issue resolved.
I thought I had lost my ETH but 
the MDO site Crypto.com (http://platinum.crypto.com/r/tme4hbch8s) does not support smart contracts for automatic account crediting.  So it takes a few days for them to process.

Be sure to check that outside wallets for erc20 or Eth support the smart contracts first."

**Comment by 0xmoehau** [comment]
closed. fixed.
