### ISSUE TITLE
Can not to detect SSID

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#221]
**Environment:** Mainnet
IOS version 13

**Steps:**
1. Go to set up the node device
2. Go to wifi

**Actual result:** the wifi name is shown such as: Can not to detect SSID

**Comment by 0xwendigo** [comment]
I have already checked this case. this bug was come from IOS OS and another good news from Apple that they fix for this issue on iOS 13.3 beta version.
For now the app will show a more friendly message instead of 'Can not to detect SSID '.
