### ISSUE TITLE
Trade without depositing/ withdrawing 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#224]
From: Abu 

I don’t know whether you already have any near plan for trade without depositing/withdrawing (like Binance chain, EOS dex’es) but you should really have. This etherdelta-style trading refrains the beginner/novice users.

**Comment by annie-incognito** [comment]
In fact, I meant one-click trading like Newdex (EOS) or Binance DEX. Currently, to trade, a user must deposit first then buy/sell and optionally withdraw. Totally it has 3 actions (deposit, trade, withdraw). I think this process may be reduced to just one action (tap/click). Besides, deposit and withdrawal takes some time which makes trading experience worse.

**Comment by 0xmoehau** [comment]
closed.
