### ISSUE TITLE
pNode - Set up is stuck at 3rd step

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#225]
User @HoopsterNYC Nokia 6.1 Android 9 app 3.33
After 3rd step, it returns back to 1st step. 
![photo_2019-12-03_16-38-04](https://user-images.githubusercontent.com/57339122/70038744-596c7780-15eb-11ea-8507-ddc61c290e3f.jpg)
![photo_2019-12-03_16-38-10](https://user-images.githubusercontent.com/57339122/70038745-5a050e00-15eb-11ea-8fec-530204cc7858.jpg)

**Comment by annie-incognito** [comment]
from: Ed

![image](https://user-images.githubusercontent.com/56621844/70043278-c20b2280-15f2-11ea-8280-bc45149ae1d9.png)

**Comment by annie-incognito** [comment]
From: Ross Taylor 

![image](https://user-images.githubusercontent.com/56621844/70043528-3b0a7a00-15f3-11ea-8091-d78e064e32f9.png)

**Comment by 0xwendigo** [comment]
Hi @peterincognito , please update the new version 3.3.5 and to retry installing the pNode again, then let me know your result.

**Comment by peterincognito** [comment]
Thanks, I will tell the user to try again when 3.3.5 is available on the appstore

**Comment by 0xmoehau** [comment]
relate to #259
