### ISSUE TITLE
Hide unused trading pair on pDEX

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#226]
We should hide PRV/pDAI, PRV/pBUSD, etc.. because it is using for mapping - network fee. It is not used for trading.
![image (3)](https://user-images.githubusercontent.com/57339122/70040657-81110f00-15ee-11ea-8f7c-b72d3159ba10.png)

**Comment by 0xSiris** [comment]
We have added liquidity for these pairs. So I will close this issue
