### ISSUE TITLE
transaction fee: user input their number 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#23]

**Comment by keresh93v** [comment]
- [ ] Support multiples fee types
 - PRV
 - Current token (must have exchange rate), will be used as a default

- [ ] Enter Amount + Address => Estimate fee
- [ ] Update Amount or Amount => re-estimate fee
- [ ] Change fee type => re-estimate fee
- [ ] After getting fee, can change fee by press on "Change the fee"
 - Input new fee (number, must be larger than estimated fee, smaller than this token's balance)
