### ISSUE TITLE
make node status between app and chain consistent 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#239]
From: thaibao 

có 1 solution tổng quan thế này
khi add node vào
ban đầu hãy call API getblockchaininfo của node mình add
nếu nó timeout -> timeout
call ko dc -> offline
nếu call dc
thì nó sẽ trả ra height của beacon cái cục shard -1 ấy
sau đó call getblockchaininfo của full node
nếu 2 cái height gần bằng nhau cho là chênh nhau 2 block đi
thì lúc đó chắc chắn node của mình đã sync data gần bằng fullnode rồi
-> mình tuỳ ý call stakerstatus, mininginfo, … này nọ vào cái node
còn nó ko cách nhau 2 block, nghĩa là vẫn còn đang sync, nó sẽ ko thể trả lời chính xác là đã stake chưa, đã earning chưa ….
-> mình show syncing
đó là giải pháp cho việc hiện hay ko hiện Tab to stake
, button run

**Comment by 0xmoehau** [comment]
closed, because duplicate.
we re-design new status flow at 12/10/2019
