### ISSUE TITLE
pNode is "earning" for 24 hours but no reward

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#247]
From: Justin Smith
Node QR: 1240-414347
Description: 
"I’ve been in earning mode for over 24 hours but haven’t earned anything. I just keep waiting but nothing."
If the status is "earning", there should have a reward after 1 epoch ~ 4 hours. Please help to explain.
![photo_2019-12-05_20-01-51](https://user-images.githubusercontent.com/57339122/70237606-26b4b180-179a-11ea-9e91-9e6e06d038a0.jpg)

**Comment by 0xmoehau** [comment]
@peterincognito closed.
