### ISSUE TITLE
node home page: add earnings in different currencies

### ISSUE THREAD

**Issue by screensav3r** [incognitochain/incognito-wallet#251]
show all currencies on node home page.

![image](https://user-images.githubusercontent.com/57341808/70424803-9086d100-1aa2-11ea-8732-26c14b9c009d.png)
![image](https://user-images.githubusercontent.com/57341808/70424819-954b8500-1aa2-11ea-8f4d-7b24aa212af5.png)

**Comment by screensav3r** [comment]
dont do this - new ui incoming

**Comment by 0xmoehau** [comment]
#275
