### ISSUE TITLE
make it clearer that FTM is ERC 20 token

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#253]

**Comment by annie-incognito** [comment]
![image](https://user-images.githubusercontent.com/56621844/70434264-54f60200-1ab6-11ea-9b68-48448cfc54c4.png)
Instead of Fantom token, to use the token standard: ERC20

**Comment by 0xmoehau** [comment]
closed. click to detail Token.  
Duplicate #33
