### ISSUE TITLE
New workflow Setup Node

### ISSUE THREAD

**Issue by 0xwendigo** [incognitochain/incognito-wallet#259]
![20191206_144635](https://user-images.githubusercontent.com/24999486/70498202-37717880-1b48-11ea-998f-7ee9b525d135.jpg)

**Comment by 0xwendigo** [comment]
- [ ] Move Qrcode step -> the first step.
- [ ] Hold all input value if Node setup failed.
- [ ] App connect new name's hotspot.
- [ ]: #70 :When inputting wrong name wifi or wrong password. => will go to this step which input wifi info.

**Comment by 0xwendigo** [comment]
- [ ]  Keep track log in the step by step.
- [ ]  Use QRcode to assign the wallet's name.
- [ ]  Save Node info when node successfully signs in firebase.

**Comment by 0xmoehau** [comment]
commit release 12/19/2019 @0xwendigo @annie-incognito @peterincognito

**Comment by 0xmoehau** [comment]
releated #70 #69

**Comment by 0xmoehau** [comment]
related to #272

**Comment by 0xwendigo** [comment]
fixed #299

**Comment by 0xwendigo** [comment]
fixed #301

**Comment by 0xwendigo** [comment]
related to #275
