### ISSUE TITLE
For number input fields: user has a german keyboard that doesn't allow him to put . only ,

### ISSUE THREAD

**Issue by screensav3r** [incognitochain/incognito-wallet#261]
USER: @johnyqi

DESCRIPTION: 

for different devices/countries (for example, in germany, only a comma appears on the keyboard, instead of a dot - so user cannot input 10.008 if he wants, only 10,008 - he has to copy paste a dot from somewhere else).

CONVO: 

Maybe your devs can fix the issue with dot and comma. I have to copy paste a dot to be able to put in the price properly. I’m on German device, so is pulling German numerics, I guess. But your app should be able to adapt.

![image](https://user-images.githubusercontent.com/57341808/70504353-33e5ed80-1b58-11ea-9cae-0a7746fb5212.png)

**Comment by 0xSiris** [comment]
this issue is duplicated with https://github.com/incognitochain/incognito-wallet/issues/209
