### ISSUE TITLE
Form Submit PApp.

### ISSUE THREAD

**Issue by 0xmoehau** [incognitochain/incognito-wallet#268]
Submit a pApp.

![image](https://user-images.githubusercontent.com/24519394/70632729-f53c5a00-1c61-11ea-89b7-5813a74a8501.png)

Name
Link
Short description(80 char)
Full description (4000 char)
Logo (submit)
Image[1-5] (submit)  

To earn a verified badge (?), please fill in these fields (optional):

Creator
Enter creator name

Website
Enter project or coin URL

Email address
Enter the official email address for your pApp or project

**Comment by hoangphuongcs** [comment]
Name
Link
Short description(80 char)
Full description (4000 char)
Logo (submit)
Image1 (submit)
...
Image5 (submit)
Email

**Comment by hoangphuongcs** [comment]
done: dec 23
