### ISSUE TITLE
UI bug -> hard to get rid of keyboard 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#278]
From: @johnyqi
Description:
One UI bug, it took me some time to get rid of the keyboard so that I can tap on the send button. Basically the only way to do it is to tap on address and tap enter.
![image](https://user-images.githubusercontent.com/56621844/70702798-71d24580-1d01-11ea-86c2-72b26b0f096c.png)

**Comment by 0xSiris** [comment]
This will be fixed in #3.6.6
