### ISSUE TITLE
Wallet app closes on finalizing transactions

### ISSUE THREAD

**Issue by Just-m** [incognitochain/incognito-wallet#286]
When the user (Telegram Tanvir (@Shakib239)), tries to transfer funds the app closes
on this screen
![image](https://user-images.githubusercontent.com/5701553/70735323-4efa5e00-1d0e-11ea-9b62-57992bf53377.png)

Tried on different devices. Samsung,redmi,realme

Device details of one device:
![image](https://user-images.githubusercontent.com/5701553/70735352-5f123d80-1d0e-11ea-8529-7b83be49d2fb.png)

![image](https://user-images.githubusercontent.com/5701553/70735366-66394b80-1d0e-11ea-9a12-7c71f1e3ace7.png)

**Comment by 0xSiris** [comment]
duplicated #302
