### ISSUE TITLE
Hot_fix pNode status earnning

### ISSUE THREAD

**Issue by 0xmoehau** [incognitochain/incognito-wallet#290]

**Comment by screensav3r** [comment]
theres a typo for i think pnode? 

proccessing -> processing

should we change this to queueing?

**Comment by 0xwendigo** [comment]
this is ticket which supports the old version of node.

**Comment by 0xwendigo** [comment]
> theres a typo for i think pnode?
> 
> proccessing -> processing
> 
> should we change this to queueing?

it was changed in build 3.4.1
