### ISSUE TITLE
vnode stt - showing confusing 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#299]
- node staked earning for two weeks -> showing online
- node queueing blue vs node queueing grey -> meaning? 

![image](https://user-images.githubusercontent.com/56621844/70878916-08e71800-1ff6-11ea-814f-7149cb1da047.png)

**Comment by 0xwendigo** [comment]
> node queueing blue vs node queueing grey -> meaning? => my mistake, dont care about this.

**Comment by 0xwendigo** [comment]
![code-node](https://user-images.githubusercontent.com/24999486/70886356-e5c86280-200d-11ea-8ba0-856a592ec096.png)
Please find the attached file.

**Comment by 0xwendigo** [comment]
finally, I will edit as below file.
![Screen Shot 2019-12-16 at 2 44 53 PM](https://user-images.githubusercontent.com/24999486/70888393-d4358980-2012-11ea-80f2-6e290ac91747.png)
