### ISSUE TITLE
Duplicate amount if using same validator key for pNode & vNode

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#307]
From: Hieu Phan
Description:
He set up pNode successfully, then he uses the validator key of the pNode to run another vNode. Result in duplicating the reward. 
Binh said the reward balance for vNode should be 0. Please check.
 
![photo_2019-12-16_17-24-08](https://user-images.githubusercontent.com/57339122/70899275-e6babd80-2028-11ea-84f0-1e6747b39384.jpg)

**Comment by 0xSiris** [comment]
This has been fixed in #356
