### ISSUE TITLE
Create privacy token - UX logic change

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#33]
- [x] add filter token, chain, network 
- [x] remove duplicate icon native token <> privacy token. 
- [x] add token's chain-name.
- [x] token id or address 
- [x] privacy token ICON default.
- [x] change UI color of header bar in screen detail-token for privacy token detail.
- [x] add description privacy token.
- [x] add total supplier privacy token.

**Comment by annie-incognito** [comment]
request UI from designer

**Comment by 0xmoehau** [comment]
Will people be able to create tokens that already exist, or has that been taken care of already? Or will the system know the difference between them?

**Comment by keresh93v** [comment]
It'll be done before 16h30 Nov 22th, 2019

**Comment by keresh93v** [comment]
These sub-tasks will be completed next Monday, have to wait for support from the Chain. 
- add description privacy token.
- add owner token address

Move the task "upload the privacy icon" to todo list.

**Comment by 0xmoehau** [comment]
closed , update to #269
