### ISSUE TITLE
Request failed with status code 503

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#333]
From: @CodedInk @Night1Wolf
Description:
Request failed with status code 503
https://github.com/incognitochain/incognito-chain/issues/640
![photo_2019-12-19_12-09-04](https://user-images.githubusercontent.com/57339122/71146651-afcaee80-2258-11ea-92aa-94a20e1d4474.jpg)

**Comment by peterincognito** [comment]
Phuong said this should be related to the 503 error above:
![photo_2019-12-19_12-13-42](https://user-images.githubusercontent.com/57339122/71146755-0d5f3b00-2259-11ea-9146-4644c152df67.jpg)

**Comment by 0xSiris** [comment]
This has been fixed in #356
