### ISSUE TITLE
Don't request Stake although node is set up success in device

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#343]
**Pre-condition:**
The device connects low network

1. Go to app
2.Select Node
3.Scan QR code
4. Enter name and password wifi
5. Click next button

**Expected result:** User can set up node success. The information is saved in database and sent to slack. 
**Actual result:** User can set up node success. The information is NOT saved in the database and sent to slack.

**Comment by hoangphuongcs** [comment]
Alway request stake if dont have any request stake or request failed/timeout ...
