### ISSUE TITLE
Reverse trade pair feature

### ISSUE THREAD

**Issue by abduramann** [incognitochain/incognito-wallet#349]
Reversing trade pair easily would be great. For example, PRV->USDT is open in pDEX, then the user wants to trade USDT->PRV. She should be able to this change in one tap. As a suggestion, the arrow in the middle of two coins may be used for this feature.

**Comment by 0xSiris** [comment]
We are testing this feature. It will release soon. After that You can click on the middle arrow to swap input and output

**Comment by 0xSiris** [comment]
This has been fixed in #356
