### ISSUE TITLE
withdraw to eth external wallet address not working 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#380]
From: Ross Taylor

Wallet address: 0x21977516136b2f352c7d4cB598c9df69034de4c5

Ross Taylor, [06.01.20 09:57]
It doesn’t give me a message it just won’t calculate the fee
So there I cannot hit the withdraw button because it is inactive
This is when trying to withdraw to an external wallet from account not a node

**Comment by 0xmoehau** [comment]
release #577
