### ISSUE TITLE
Token label is disappeared on the app screen

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#39]
Every time the user restarts the app, pBTC, pETH, and pTOMO are disappeared respectively. 
It happens on both iOS and Android. 
![photo_2019-11-05_14-39-40](https://user-images.githubusercontent.com/57339122/68187791-2cbc4480-ffda-11e9-9c61-846ce6bf2c43.jpg)
![photo_2019-11-05_14-39-45](https://user-images.githubusercontent.com/57339122/68187804-334abc00-ffda-11e9-939a-943fb96d867a.jpg)
![photo_2019-11-05_14-39-47](https://user-images.githubusercontent.com/57339122/68187810-35ad1600-ffda-11e9-80cc-f2f36f3226d4.jpg)

**Comment by keresh93v** [comment]
Fixed.
