### ISSUE TITLE
Withdraw works incorrect with -4007 when withdrawing money from Pdex which screen is off

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#423]
Steps:
1. Go to Pdex
2. Withdraw money
3. Waiting for the screen is off

Actual result: The error 4007 is shown. Users cannot withdraw. After that, user off popup. The tx withdrawal is created. User clicks try again button. The withdraw is a success.

Expected result: User can withdraw success without error.

**Comment by 0xSiris** [comment]
This issue is duplicated with #427
