### ISSUE TITLE
The error is shown your balance is not enough coin although the account is enough money when inputting amount in send screen

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#429]
<img width="347" alt="Screen Shot 2020-01-21 at 5 24 44 PM" src="https://user-images.githubusercontent.com/57382380/72797039-f86c3200-3c72-11ea-950a-f3c294032b22.png">

**Comment by Dream0895** [comment]
<img width="347" alt="Screen Shot 2020-01-21 at 5 24 44 PM" src="https://user-images.githubusercontent.com/57382380/72797039-f86c3200-3c72-11ea-950a-f3c294032b22.png">

**Comment by DimCreaper** [comment]
i dont know what i should be doing ive been everywhere looking for help i dont really know how i ended up here i was just looking for a good wallet and screwed it all up pls can i get some help
