### ISSUE TITLE
Couldn't withdraw

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-wallet#43]
### FROM
@Z3Y_01

### CHAT LOG
Yes from iOS.  It doesn’t show anything, just spinning wheel.
![photo_2019-11-05 16 10 49](https://user-images.githubusercontent.com/4691695/68246490-e28d9000-ffe6-11e9-837f-3a3c64cf8340.jpeg)
![photo_2019-11-05 16 10 48](https://user-images.githubusercontent.com/4691695/68246491-e28d9000-ffe6-11e9-878e-27dad5c684d3.jpeg)
![photo_2019-11-05 16 10 47 (1)](https://user-images.githubusercontent.com/4691695/68246492-e28d9000-ffe6-11e9-9221-23161e0e5c62.jpeg)
![photo_2019-11-05 16 10 47](https://user-images.githubusercontent.com/4691695/68246493-e28d9000-ffe6-11e9-8e98-841764c1a428.jpeg)
![photo_2019-11-05 16 10 46](https://user-images.githubusercontent.com/4691695/68246495-e28d9000-ffe6-11e9-84c6-24fd99b743a0.jpeg)
![photo_2019-11-05 16 10 44](https://user-images.githubusercontent.com/4691695/68246496-e28d9000-ffe6-11e9-8c56-6fd139468f89.jpeg)
![photo_2019-11-05 16 10 43](https://user-images.githubusercontent.com/4691695/68246497-e3262680-ffe6-11e9-9055-c1287c14bc42.jpeg)
![photo_2019-11-05 16 10 42](https://user-images.githubusercontent.com/4691695/68246499-e3262680-ffe6-11e9-8fcb-8fc804a282c7.jpeg)
![photo_2019-11-05 16 10 37](https://user-images.githubusercontent.com/4691695/68246501-e3262680-ffe6-11e9-8c9a-8e20e89c786c.jpeg)

**Comment by annie-incognito** [comment]
From:  @Night1Wolf


![photo_2019-11-07_08-32-35](https://user-images.githubusercontent.com/56621844/68357573-63b06880-0148-11ea-80eb-4d2b7f731841.jpg)


iOS 

Uninstall then re install works.

**Comment by 0xmoehau** [comment]
please update the app. this issue has been fixed.
