### ISSUE TITLE
Prevent accounts with the same name in one wallet

### ISSUE THREAD

**Issue by Just-m** [incognitochain/incognito-wallet#444]
Once two accounts have the same name (different address) in the same wallet, you are no longer able to remove either one of them.

**Comment by 0xSiris** [comment]
How did user have  two account with same name? Because if user create/import account with existing name. They will get error.

**Comment by peterincognito** [comment]
Hi @Just-m , would you please provide more information about this bug?

**Comment by 0xSiris** [comment]
I will close this issue due to a lack of information
