### ISSUE TITLE
"Missing account" on pNode

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#451]
From: J Z
Description:
The Node says "Missing account", but he had the wallet on his phone. ID: 5550-573746
![image](https://user-images.githubusercontent.com/57339122/74403712-d1141980-4e5a-11ea-972e-df6655502473.png)
![image](https://user-images.githubusercontent.com/57339122/74403735-f143d880-4e5a-11ea-984f-9989cfc24427.png)
![image](https://user-images.githubusercontent.com/57339122/74403740-f739b980-4e5a-11ea-93f1-b806d6fabb50.png)

**Comment by 0xSiris** [comment]
The payment address is invalid. We have udpated it
