### ISSUE TITLE
Send/withdraw buton are enabled athough user input wrong information when switching wrong data to valid data and wrong data.

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#482]
Steps:
1. Go to send/withdraw
2. Input all required fields and Input mix-1/float(Incognito token/Neo token) in amount => The warning message is shown
3. Input valid data( min, int)
4. Input wrong data

Expected result: Send/withdraw button is disabled.
Actual result: Send/withdraw button is enabled.

**Comment by 0xmoehau** [comment]
release #3.6.5.5
