### ISSUE TITLE
[3.2.3, Android] Can't stake

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-wallet#49]
### FROM

@fitz_fiat

### LOG

I tested the android 3.2.3 to start staking and it crashes.   Also the 3.2.0 iOS is crashing as well on my iPhone XR.
However my iPad Pro 9.7” is working well.  I can’t tell the version on my iPad and it may be newer or older than the iPhone.

**Comment by 0xwendigo** [comment]
- Estimate Fee Component.

**Comment by 0xwendigo** [comment]
duplicate #53
