### ISSUE TITLE
Incognito staking pool 

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-wallet#51]
- staker send prv to pool.
- Node validator request prv for run the node. 

- [x] Create a stake request (api)
- [x] Get a stake request (api)
- [x] Update a stake request (api)
- [x] Create a tool to update stake (mark staked / rejected) (tool)
- [x] Create a staker contribute  (api)
- [x] Add contribute  (api)
- [x] Stop contribute  (api)

**Comment by hoangphuongcs** [comment]
will be done by nov 22, 2019
