### ISSUE TITLE
Stake then crash  - iOS 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#53]
From: @bluemoose_ben

Chat log: 
Annie, [07.11.19 11:38]
Which device do you use?

Ben Musson, [07.11.19 11:39]
Sure thing. For the app, I'm on an iPhone XS Max. I'm running iOS 13.2.

Ben Musson, [07.11.19 11:39]
I just upgraded to 13.2 today - I wanted to see if that had any effect on the bug, but no.

Annie, [07.11.19 11:43]
So it still crashes when you hit stake?

**Comment by annie-incognito** [comment]
Right. I tap into the node to stake, hit Run, and the screen flashes white and the app crashes. It was doing that on the last app version as well, but I thought it might be because I was trying to stake from a different address than the node's validator key but couldn't send the PRV to the correct address to check.

**Comment by peterincognito** [comment]
zhongbencong
--
App is crashed after clicking on "run" button
Device: Galaxy tab S3
Android 9
--
Wallet address: 12S66dH8MEgDpP9QUvFXP7nBb52qgXqiRcwiR2QPewnuKagJarmWgSXwm6m9MSTcv1utoRYTjMxxPLFpqXCtzuoVpiZ9xhhBjqeB21Z
IP: 104.248.151.245

**Comment by screensav3r** [comment]
Beau Smith

i just go to hit run and it immediately crashes. I tried uninstalling and reinstalling. Also deleted my node. No effect.
