### ISSUE TITLE
Cannot stake although the new account has 1750 PRV

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#62]
Pre-condition: 
+ Virtual node is added my nodes and import private key
+ Account has 1750 PRV 

Steps:
1. Click run button
2. Click Slake button

Actual result: The screen is loading for 10 %. After that the pop-up is disappeared.

**Comment by alexpmorris** [comment]
I'm having the same problem, except I don't even get to 10%, app crashes immediately after clicking "RUN".  Running version 3.2.3, no new updates appear to be available yet.

**Comment by Dream0895** [comment]
Hi @alexpmorris ,

Thanks for your feedback!
Your issue was fixed in 3.2.4. Please update the new version to use. This issue only happened when we have an amount equal to 1750 PRV. 
Please let me know if you have any. We will log it on another ticket.
Many thanks.
