### ISSUE TITLE
TOMO - Missing deposit

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#68]
User: nguyenbk92@gmail.com
Deposit 11 tomo to his incognito address but it is not shown. This is the txid: https://scan.tomochain.com/txs/0x0c996d209dcbd5edea2588dabc6b9377d45b81bf6a578ce8ccd3168df331587c
![image0](https://user-images.githubusercontent.com/57339122/68571585-e2cdd580-0495-11ea-8c67-0fdc3e064349.jpeg)
Please help to check.

**Comment by hoangphuongcs** [comment]
Remove this token pTomo, and follow token pTOMO in tab COIN
