### ISSUE TITLE
Failed eth withdrawal

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#75]
User @Necroths has 0.99 pETH in balance. He wants to withdraw 0.17 pETH to outside wallet: 0xAd5EF4d3F33C749ffE6C50E9F7F88b9669a28CC6
On 6:19 he sent 0.17 pETH to [15pABF...BrNfs]
Txid: https://mainnet.incognito.org/tx/59333c998a206e99621faf150f46588bbdfeb6279538266de893cc309e7cf4c5
![photo_2019-11-12_11-19-23](https://user-images.githubusercontent.com/57339122/68641760-63481100-053e-11ea-96ef-4b45fd65a24d.jpg)
On 6:49 he withdraw 0.17 ETH to his own address [12RuShgmx41V3uEVcxVn5dfVwRXT4ccYTMHW7eaBBggWLFL7LZ5XMwUdTUXcL3JKseE49zB5s3VHsKz1BkuaBeT9SegArhQkWNUHm2J]
Txid: https://mainnet.incognito.org/tx/59333c998a206e99621faf150f46588bbdfeb6279538266de893cc309e7cf4c5
![photo_2019-11-12_11-25-53](https://user-images.githubusercontent.com/57339122/68642013-3f38ff80-053f-11ea-8317-6428cb789888.jpg)

His balance is now 0.82 pETH. Please help to locate the issue. 
![photo_2019-11-12_11-20-43](https://user-images.githubusercontent.com/57339122/68641968-16186f00-053f-11ea-988e-e0a935d31fd2.jpg)

**Comment by 0xmoehau** [comment]
smart-contract paused.
it's will back in the next 4 hours.
