### ISSUE TITLE
Send TX with a custom message.

### ISSUE THREAD

**Issue by 0xmoehau** [incognitochain/incognito-wallet#81]
- allow user input messages in a transaction. 
- option privacy / none privacy tx.

**Comment by granthawkins88** [comment]
For PRV, there is still no record of received transactions (https://github.com/incognitochain/incognito-wallet/issues/31)

Custom message will be useless for PRV until received transactions are visible.

**Comment by 0xmoehau** [comment]
will be done at 11/26/2019  @keresh93v
