### ISSUE TITLE
The estimate fee is increased high when having an account which pays fee more in shard

### ISSUE THREAD

**Issue by Dream0895** [incognitochain/incognito-wallet#91]

**Comment by Dream0895** [comment]
[
![screenshot_2019-11-15-13-22-04-54](https://user-images.githubusercontent.com/57382380/68924376-4700da00-07b3-11ea-9d56-038d81a99c1f.png)
](url)

**Comment by 0xSiris** [comment]
The estimate fee is calculated by average fee of 5 latest blocks. So in this case, it worked correctly
