### ISSUE TITLE
Reduce minimum amount in sending BTC

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#92]
Now, the minimum amount for BTC is 0.0001 (~ 0.8$ -1$)
![Image from iOS (13)](https://user-images.githubusercontent.com/57339122/68924672-ec1bb280-07b3-11ea-8a61-b686f7e66ede.png)
I suggest that we should think about reducing this number to 0.00001
Please advise.

**Comment by 0xSiris** [comment]
This issue has been resolved
