### ISSUE TITLE
Node stop earning 

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#99]
From: Ning 
Description: Node showed stop earning - all earning disappeared on app. 

Node IP in the photo below:
Wallet address: 12S6VfAWX3WyUskGvE3i6Lk4RqTPdtQmeCXVRdfBvyBmzTszWWJ8s2yXsH71rMK1QZYeKj5moSw37LbA5W6qmpbcBWBH8o9sNyDaxN4

![image](https://user-images.githubusercontent.com/56621844/69024022-8cabe580-09f3-11ea-977e-32ae52ffc809.png)

**Comment by 0xwendigo** [comment]
I have already verified it. We will implement it in the next time.

**Comment by 0xmoehau** [comment]
I closed it because this VM has been stopped on Gcloud. Just re-launch a new VM.
